package app;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import org.springframework.web.bind.annotation.CrossOrigin;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import app.Pet;
import app.PetRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/pets") // This means URL's start with /demo (after Application path)
public class PetController {

	private static final Logger logger = LoggerFactory.getLogger(PetController.class);

	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PetRepository petRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewPet (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		Pet n = new Pet();
		n.setName(name);
		n.setEmail(email);
		petRepository.save(n);
		logger.info("Added: " + n.toString());
		return "Saved";
	}

	// @CrossOrigin(origins = {"http://localhost:3000"})
	@CrossOrigin(origins = {"https://react-app-mc.herokuapp.com"})
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Pet> getAllPets() {
		// This returns a JSON or XML with the users
		return petRepository.findAll();
	}

}
